export const COLLEGES = [
  "BITS Pilani",
  "BITS Pilani, Goa Campus",
  "BITS Pilani, Hyderabad Campus",
  "BITS Pilani, Dubai Campus",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "Delhi Technological University (DTU)",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "VIT Vellore",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Thapar Institute of Engineering and Technology",
  "RV College of Engineering",
  "BMS College of Engineering",
  "PES University",
  "Jadavpur University",
  "Anna University",
  "Osmania University"
];

export const DEFAULT_DEPARTMENTS = [
  "Information Technology (IT)",
  "Computer Science Engineering (CSE)",
  "Computer Science",
  "Computer Science & AI",
  "Artificial Intelligence",
  "Artificial Intelligence & Data Science",
  "Artificial Intelligence & Machine Learning",
  "Data Science",
  "Cyber Security",
  "Electronics & Communication",
  "Electronics Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Biomedical Engineering",
  "Industrial Engineering",
  "Production Engineering",
  "Mining Engineering",
  "Metallurgical Engineering",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Automobile Engineering",
  "Marine Engineering",
  "Architecture",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Statistics",
  "Economics",
  "Commerce",
  "Management",
  "MBA",
  "MCA",
  "BCA",
  "BBA",
  "English",
  "History",
  "Political Science",
  "Psychology",
  "Law",
  "Pharmacy",
  "Agriculture",
  "Design",
  "Animation",
  "Fashion Technology",
  "Hotel Management",
  "Media Studies",
  "Education"
];

export const COLLEGE_DEPARTMENTS: Record<string, string[]> = {
  // If specific colleges have unique lists, add them here.
  // Otherwise it falls back to DEFAULT_DEPARTMENTS.
  "BITS Pilani": [
    "Computer Science",
    "Electrical & Electronics",
    "Electronics & Instrumentation",
    "Mechanical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Manufacturing Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Economics",
    "Biology",
    "Pharmacy",
    "Management"
  ],
  "BITS Pilani, Goa Campus": [
    "Computer Science",
    "Electrical & Electronics",
    "Electronics & Instrumentation",
    "Electronics & Communication",
    "Mechanical Engineering",
    "Chemical Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Economics",
    "Biology"
  ],
  "BITS Pilani, Hyderabad Campus": [
    "Computer Science",
    "Electrical & Electronics",
    "Electronics & Instrumentation",
    "Electronics & Communication",
    "Mechanical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Economics",
    "Biology",
    "Pharmacy"
  ]
};

export const getDepartmentsForCollege = (collegeName: string): string[] => {
  return COLLEGE_DEPARTMENTS[collegeName] || DEFAULT_DEPARTMENTS;
};
